name: Deploy examples to gh-pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    name: 'Build and Deploy Examples to gh-pages'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - run: npm install
      - name: Build Examples
        run: npm run build
        working-directory: examples
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          GOOGLE_MAPS_MAP_ID: ${{ secrets.GOOGLE_MAPS_MAP_ID }}
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/dist
